### ISSUE TITLE
Latest version of lodash broke the template system

### ISSUE THREAD

**Issue by martinheidegger** [mdunisch/lololodash#16]
As mentioned in https://github.com/nodeschool/discussions/issues/900 the lodash version used by `lololodash` uses a templating system that is incompatible to the latest version of lodash. If someone tries to verify his solution with the newer lodash version installed locally the output will be undefined.

**Comment by mdunisch** [comment]
Thank you for pointing this out.
I take a quick look and it seems like the template-syntax change in 3.0 (https://github.com/lodash/lodash/wiki/Changelog)

Todo:
- Update Exercise.md files (new syntax)
- Update lolodash-deps
- Testing

**Comment by mdunisch** [comment]
fixed in https://github.com/mdunisch/lololodash/commit/68bbf48d79f0b7dccbe76fe76a02b7dc7c21d4dc
