### ISSUE TITLE
Spelling mistakes in exercise.js

### ISSUE THREAD

**Issue by matachines** [mdunisch/lololodash#20]
Hi, I was working on exercise 9 and noticed misspellings in the input JSON file and found them in the file exercise9.js, line 26:

```
todo: "Contibute to an Open-Sorce-Project",
```

`Contibute` should be `Contribute` and `Sorce` should be `Source`.

EDIT: Found another one, line 16:

```
todo: "Lean Lo-Dash",
```

`Lean` should be `Learn`.

**Comment by mdunisch** [comment]
Thank you @matachines!
I correct the file and it will be included in the next Release!
