### ISSUE TITLE
"Official" Solution 3 Seems Awkward for a Beginner

### ISSUE THREAD

**Issue by mist83** [mdunisch/lololodash#30]
Just my 2 cents, but

The problem requests a solution in the following order:
- over 1 million
- less than 1 million but more than 0.5
- less than 0.5

The solution answers it in a different order:
- over 1 million
- less than 0.5
- less than 1 million but more than 0.5

Doing it this way is not only different than the flow of the written description of the problem, it also forces you to mix operators (greater than and then less than) instead of a smooth, consistent "greater than 1M / greater than 0.5M / else."

Slightly related (but nitpicky): the way the question is worded, it precludes assigning a "size" property to cities that are exactly 1M or 0.5M in population.

**Comment by mdunisch** [comment]
Thank you @mist83 for pointing this out! You are totally right, I changed the solution!
