### ISSUE TITLE
Solution 5 can be done in one map

### ISSUE THREAD

**Issue by binoy14** [mdunisch/lololodash#39]
The solution provided for problem 5 doesn't need the second map function, string concatenation and upper case can be done in one map function.

```javascript
var _  = require('lodash');

var chained = function(item) {
	return _.chain(item)
		.map(function(o) {
			var newStr = o + 'Chained';
			return newStr.toUpperCase();
		})
		.sortBy()
		.value();
};

module.exports = chained;
```

Is there a reason for not doing it this way?

https://github.com/mdunisch/lololodash/blob/master/exercises/5_chain_mail/solution/solution.js#L10

Thanks

**Comment by mdunisch** [comment]
Hi @binoy14,

this exercises is about chaining. You're right, a second map isn't necessary. But I think in this case it's good to show how chaining work.
