### ISSUE TITLE
3: In Every Case - instructions for "med" says 0.58, but checks for 0.5

### ISSUE THREAD

**Issue by craig-o-curtis** [mdunisch/lololodash#47]
Instructions have slight typo that causes failure:

    ## Your Mission

    Please write a function that takes in a hashtable or associative array of
    European towns with their populations in millions:

        { Hamburg:    { population: 1.698 },
          Strasbourg: { population: 0.272 },
          Rome:       { population: 2.753 },
          Dublin:     { population: 0.528 } }

    We want a new size attribute added to every town where the value depends on
    the town's population, as follows:

        { City1: {population: 1.58, size: 'big'  },
          **City2: {population: 0.58, size: 'med'  },**
          City3: {population: 0.28, size: 'small'} }

But the verifier / answer says it is looking for a number greater than 0.5

![screen shot 2018-06-06 at 9 00 58 pm](https://user-images.githubusercontent.com/12050799/41077678-f12c6aa2-69cc-11e8-97d5-24d92515f99b.png)

![screen shot 2018-06-06 at 9 03 26 pm](https://user-images.githubusercontent.com/12050799/41077709-1d7e6ede-69cd-11e8-8601-3fc2e4d159ad.png)

**Comment by mdunisch** [comment]
hi @craig-o-curtis ,
I don't get the problem. 0.58 is bigger than 0.5.

Can you please try to explain the problem to me again?
